# Generated by Django 5.2.4 on 2025-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_category",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_currency",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
