# Generated by Django 5.2.4 on 2025-08-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_transaction_transaction_type_goal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="deadline",
            new_name="goal_deadline",
        ),
        migrations.RenameField(
            model_name="goal",
            old_name="name",
            new_name="goal_name",
        ),
        migrations.RenameField(
            model_name="goal",
            old_name="target_amount",
            new_name="goal_target_amount",
        ),
    ]
